### ISSUE TITLE
_tkinter.TclError:

### ISSUE THREAD

**Issue by Dev-0618** [CHEGEBB/IMEI-TRACKER#1]
Hey mate am new to termux I have tools but am new to much more deeper concepts 
At first it showed tkinter error which i solved by installing pkg but now

python3  CyberTrack.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/IMEI-TRACKER/CyberTrack.py", line 130, in <module>
    root = Tk()
           ^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/tkinter/__init__.py", line 2326, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: no display name and no $DISPLAY environment variable

Tell a sol please

**Comment by CHEGEBB** [comment]
It looks like you're encountering a Tkinter error related to the display environment. In a headless environment like Termux, Tkinter might not work as expected due to the absence of a graphical display.To address this issue, you can try using a virtual display such as Xvfb (X Virtual Framebuffer) to create a fake display for Tkinter. Follow these steps:Install the necessary packages in Termux:
pkg install xvfb x11-repo
pkg install python-tk

Set up the virtual display using

 Xvfb:Xvfb :1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
export DISPLAY=:1

Now run your Python script again:

python3 CyberTrack.py

This should create a virtual display for Tkinter to work with. If you still encounter issues, make sure to adjust the display settings accordingly.Keep in mind that running graphical applications in a headless environment might have limitations, and some features of Tkinter may not behave as expected.I will also create a version that works superbly in termux or doesn't use a gui for operation.

**Comment by CHEGEBB** [comment]
I  also updated the project with a version that runs in termux try running 👍

Python3 Track. py
